task/home_work_7
MrSpock99/homework_android pull request #3
Opened 2018-11-11 10:36 UTC by MrSpock99

2018-11-11 20:29 UTC, NailShaykhrazievItis requested changes

2018-11-11 20:29 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/androidhomework/MyMusicRecyclerViewAdapter.kt
> +
extra line

2018-11-11 20:29 UTC, NailShaykhrazievItis commented on app/src/main/java/apps/robot/androidhomework/fragments/MusicListFragment.kt
> +        if (view is RecyclerView) {
Очень странный код, прям зачееем. Вопросы без ответа

2018-11-11 20:43 UTC, MrSpock99 commented on app/src/main/java/apps/robot/androidhomework/fragments/MusicListFragment.kt
> +        if (view is RecyclerView) {
хз, студия сама сгенерировала, выглядит прикольно

2018-11-11 20:49 UTC, MrSpock99 commented
![screenshot_9](https://user-images.githubusercontent.com/15799949/48318088-74e59880-e60c-11e8-9df0-f064ab858563.png)
![screenshot_7](https://user-images.githubusercontent.com/15799949/48318089-74e59880-e60c-11e8-8b97-93a1c8553eda.png)
![screenshot_8](https://user-images.githubusercontent.com/15799949/48318090-74e59880-e60c-11e8-8314-e54a62a5eae9.png)
![screenshot_6](https://user-images.githubusercontent.com/15799949/48318091-7911b600-e60c-11e8-9055-43215bc17411.png)

2018-11-12 12:24 UTC, NailShaykhrazievItis approved these changes

2018-11-20 04:02 UTC, closed without merging